<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260208083746 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE currency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_code VARCHAR(255) NOT NULL, char_code VARCHAR(255) NOT NULL, nominal INT NOT NULL, name VARCHAR(255) NOT NULL, value NUMERIC(10, 4) NOT NULL, vunit_rate NUMERIC(10, 4) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE currency');
    }
}
